// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLtRK_mpkfNrgKLEPj-Yt7UKbbzYUDya8',
    appId: '1:484971886880:web:c206fa5cbdc0c176fbbf45',
    messagingSenderId: '484971886880',
    projectId: 'smart-home-twohandm',
    authDomain: 'smart-home-twohandm.firebaseapp.com',
    storageBucket: 'smart-home-twohandm.appspot.com',
    measurementId: 'G-QHJEDDF9ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNI8hHYF2ofMmqgS-opnDgtpzM-RXkxFY',
    appId: '1:484971886880:android:55aa81f88183525ffbbf45',
    messagingSenderId: '484971886880',
    projectId: 'smart-home-twohandm',
    storageBucket: 'smart-home-twohandm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5PnCE1g-hD-j79MhfsBXQ4-2Wk2Sp_bw',
    appId: '1:484971886880:ios:78a0ffde9722c411fbbf45',
    messagingSenderId: '484971886880',
    projectId: 'smart-home-twohandm',
    storageBucket: 'smart-home-twohandm.appspot.com',
    iosClientId: '484971886880-hh8j7hrl5j5g4d68lo5i9p2186r7208l.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5PnCE1g-hD-j79MhfsBXQ4-2Wk2Sp_bw',
    appId: '1:484971886880:ios:78a0ffde9722c411fbbf45',
    messagingSenderId: '484971886880',
    projectId: 'smart-home-twohandm',
    storageBucket: 'smart-home-twohandm.appspot.com',
    iosClientId: '484971886880-hh8j7hrl5j5g4d68lo5i9p2186r7208l.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartHome',
  );
}
